

export const productSeedData = [
  { name: 'Siyah Çelik Boru DN25 (Dikişli Orta Seri)', unit: 'metre', currency: 'TRY', basePrice: 185.00, supplierName: 'Demir Çelik Tedarik A.Ş.', categoryName: 'Siyah Çelik Borular (Dikişli/Dikişsiz)' },
  { name: 'PPRC Kompozit Boru Ø25 (Cam Elyaf Takviyeli)', unit: 'metre', currency: 'TRY', basePrice: 45.00, supplierName: 'Plastik Boru Sanayi', categoryName: 'PPRC Temiz Su Boruları ve Fitingsleri' },
  { name: 'Patent Dirsek DN25 (Kaynak Ağızlı)', unit: 'adet', currency: 'TRY', basePrice: 45.00, supplierName: 'Fitings Dünyası', categoryName: 'Boru Fitingsleri (Dirsek, Te, Redüksiyon - Kaynaklı)' },
  { name: 'Çelik Flanş DN65 PN16 (Boyunlu)', unit: 'adet', currency: 'TRY', basePrice: 250.00, supplierName: 'Fitings Dünyası', categoryName: 'Boru Fitingsleri (Dirsek, Te, Redüksiyon - Kaynaklı)' },
  { name: 'Kelebek Vana DN50 (Lug Tipi)', unit: 'adet', currency: 'USD', basePrice: 85.00, supplierName: 'Vana Marketim', categoryName: 'Kelebek Vanalar (Dişli kutulu / Kollu)' },
  { name: 'Termostatik Radyatör Vanası (Köşe Tip)', unit: 'adet', currency: 'EUR', basePrice: 12.00, supplierName: 'Vana Marketim', categoryName: 'Isıtma Vana Grubu' },
  { name: 'Statik Balans Vanası DN25', unit: 'adet', currency: 'EUR', basePrice: 65.00, supplierName: 'Vana Marketim', categoryName: 'Balans Vanaları (Statik / Dinamik)' },
  { name: 'Prefabrik Boru Yalıtımı (Taşyünü 1")', unit: 'metre', currency: 'TRY', basePrice: 45.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Boru İzolasyonu (Cam Yünü / Taş Yünü / Alüminyum Kaplama)' },
  { name: 'Boru Kelepçesi 1" (Somunlu Lastikli)', unit: 'adet', currency: 'TRY', basePrice: 8.50, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Boru Askı ve Konsol Sistemleri (Rot, Dübel, Somun, L Profil)' },
  { name: 'Siyah Çelik Boru 3" (Dikişsiz Soğutma)', unit: 'metre', currency: 'TRY', basePrice: 550.00, supplierName: 'Demir Çelik Tedarik A.Ş.', categoryName: 'Çelik Borular (Soğutma Hattı)' },
  { name: 'Bakır Boru 3/8" (Klima Tipi Tavlı)', unit: 'metre', currency: 'USD', basePrice: 12.00, supplierName: 'Bakır Boru A.Ş.', categoryName: 'Bakır Borular (Sert / Tavlı)' },
  { name: 'Elastomerik Kauçuk Köpüğü 19mm Levha', unit: 'm2', currency: 'TRY', basePrice: 450.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Elastomerik Kauçuk Köpüğü İzolasyonu (Boru çapına göre et kalınlıkları detaylandırılmalı)' },
  { name: 'Kauçuk Bant 5cm (Kendinden Yapışkanlı)', unit: 'adet', currency: 'TRY', basePrice: 120.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Elastomerik Kauçuk Köpüğü İzolasyonu (Boru çapına göre et kalınlıkları detaylandırılmalı)' },
  { name: 'Motorlu Vana 2 Yollu DN25 (On/Off)', unit: 'adet', currency: 'EUR', basePrice: 110.00, supplierName: 'Kontrol Vanaları Ltd.', categoryName: 'Motorlu Vanalar (2 Yollu / 3 Yollu - On/Off veya Oransal)' },
  { name: 'Pislik Tutucu DN50 (Y Tipi Flanşlı)', unit: 'adet', currency: 'USD', basePrice: 65.00, supplierName: 'Vana Marketim', categoryName: 'Pislik Tutucular' },
  { name: 'Metal Körüklü Kompansatör DN65', unit: 'adet', currency: 'USD', basePrice: 140.00, supplierName: 'Vana Marketim', categoryName: 'Kompansatörler (Metal Körüklü / Kauçuk)' },
  { name: 'Soğuk Kelepçe Takozu 2" (Poliüretan)', unit: 'adet', currency: 'EUR', basePrice: 8.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Boru Askıları (İzolasyon Takozlu - Soğuk Köprü Engelleyici)' },
  { name: 'PPRC Temiz Su Borusu Ø20 PN20', unit: 'metre', currency: 'TRY', basePrice: 25.00, supplierName: 'Plastik Boru Sanayi', categoryName: 'PPRC Temiz Su Boruları ve Fitingsleri' },
  { name: 'Sessiz Pis Su Borusu Ø110 (3 Katmanlı)', unit: 'metre', currency: 'TRY', basePrice: 180.00, supplierName: 'Plastik Boru Sanayi', categoryName: 'Sessiz Borular (Astolan / Mineral katkılı)' },
  { name: 'PPRC Dirsek Ø25', unit: 'adet', currency: 'TRY', basePrice: 3.50, supplierName: 'Plastik Boru Sanayi', categoryName: 'PPRC Temiz Su Boruları ve Fitingsleri' },
  { name: 'Küresel Vana 1" (Pirinç Su Vanası)', unit: 'adet', currency: 'TRY', basePrice: 110.00, supplierName: 'Vana Marketim', categoryName: 'Tesisat Aksesuarları' },
  { name: 'Çekvalf 1" (Yaylı Pirinç)', unit: 'adet', currency: 'TRY', basePrice: 85.00, supplierName: 'Vana Marketim', categoryName: 'Tesisat Aksesuarları' },
  { name: 'Basınç Düşürücü 3/4" (Manometreli)', unit: 'adet', currency: 'EUR', basePrice: 45.00, supplierName: 'Vana Marketim', categoryName: 'Basınç Düşürücüler' },
  { name: 'Gömme Rezervuar Seti', unit: 'adet', currency: 'TRY', basePrice: 1850.00, supplierName: 'Vitrifiye Toptan A.Ş.', categoryName: 'Tesisat Aksesuarları' },
  { name: 'Yer Süzgeci 10x10 (Paslanmaz)', unit: 'adet', currency: 'TRY', basePrice: 250.00, supplierName: 'Vitrifiye Toptan A.Ş.', categoryName: 'Süzgeçler (Yer Süzgeci, Balkon Süzgeci, Çatı Süzgeci)' },
  { name: 'Yangın Borusu 2" (Kırmızı Astarlı)', unit: 'metre', currency: 'TRY', basePrice: 380.00, supplierName: 'Demir Çelik Boru A.Ş.', categoryName: 'Siyah Çelik Boru (SCH40 - Yivli veya Kaynaklı)' },
  { name: 'Yivli Rijit Kaplin 2" (FM/UL)', unit: 'adet', currency: 'USD', basePrice: 6.50, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Yivli Bağlantı Parçaları (Kaplin, Dirsek, Te)' },
  { name: 'Pendent (Sarkık) Sprinkler K:5.6 68°C', unit: 'adet', currency: 'USD', basePrice: 7.50, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Saha Ekipmanları (Zone Bazlı)' },
  { name: 'Islak Alarm Vanası İstasyonu DN100', unit: 'set', currency: 'USD', basePrice: 1300.00, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Islak Alarm Vanaları (Alarm Check Valve)' },
  { name: 'İzleme Anahtarlı Kelebek Vana DN100', unit: 'adet', currency: 'USD', basePrice: 220.00, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'İzleme Anahtarlı Kelebek Vanalar' },
  { name: 'Akış Anahtarı (Flow Switch) 2"', unit: 'adet', currency: 'USD', basePrice: 85.00, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Akış Anahtarları (Flow Switch)' },
  { name: 'Yangın Dolabı (Sıva Altı Tüplü)', unit: 'adet', currency: 'TRY', basePrice: 4500.00, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Saha Ekipmanları (Zone Bazlı)' },
  { name: 'Galvaniz Sac Levha 0.70mm', unit: 'kg', currency: 'USD', basePrice: 1.70, supplierName: 'Havalandırma Dünyası', categoryName: 'Galvaniz Hava Kanalları (Levha kalınlıklarına göre: 0.70mm, 1.00mm, 1.20mm)' },
  { name: 'Kanal Flanş Profili 25mm', unit: 'metre', currency: 'TRY', basePrice: 22.00, supplierName: 'Havalandırma Dünyası', categoryName: 'Hava Kanalı Flanş ve Köşe Parçaları' },
  { name: 'Kanal Köşe Parçası 25mm', unit: 'adet', currency: 'TRY', basePrice: 2.50, supplierName: 'Havalandırma Dünyası', categoryName: 'Hava Kanalı Flanş ve Köşe Parçaları' },
  { name: 'Esnek Hava Kanalı Ø200 (İzoleli)', unit: 'kutu', currency: 'USD', basePrice: 45.00, supplierName: 'Havalandırma Dünyası', categoryName: 'Kanal Aksesuarları' },
  { name: 'Yangın Damperi 400x400 (Sigortalı)', unit: 'adet', currency: 'EUR', basePrice: 150.00, supplierName: 'Havalandırma Aksesuar Ltd.', categoryName: 'Yangın Damperleri (Sigortalı / Motorlu)' },
  { name: 'Volüm Damperi 300x300', unit: 'adet', currency: 'EUR', basePrice: 60.00, supplierName: 'Havalandırma Aksesuar Ltd.', categoryName: 'Hava Damperleri (Manuel Volüm Damperi)' },
  { name: 'Toplayıcı Menfez 400x400 (Damperli)', unit: 'adet', currency: 'TRY', basePrice: 350.00, supplierName: 'Menfez Market', categoryName: 'Menfezler (Dağıtıcı/Toplayıcı - Damperli/Dampersiz)' },
  { name: 'Akustik Yalıtım Süngeri (Yanmaz)', unit: 'm2', currency: 'EUR', basePrice: 12.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Kanal İzolasyonu (Akustik / Termal - İçten/Dıştan)' },
  { name: 'Doğalgaz Çelik Borusu 1" (PE Kaplı)', unit: 'metre', currency: 'TRY', basePrice: 210.00, supplierName: 'Doğalgaz Malzeme A.Ş.', categoryName: 'Saha Enstrümanları' },
  { name: 'Doğalgaz Küresel Vanası 1" (MOP5)', unit: 'adet', currency: 'TRY', basePrice: 180.00, supplierName: 'Vana Marketim', categoryName: 'Saha Enstrümanları' },
  { name: 'Solenoid Vana 1" (Ex-Proof Manuel Kurmalı)', unit: 'adet', currency: 'EUR', basePrice: 120.00, supplierName: 'Otomasyon Market', categoryName: 'Saha Enstrümanları' },
  { name: 'Esnek Metal Hortum (Flex) 1/2"', unit: 'adet', currency: 'TRY', basePrice: 120.00, supplierName: 'Doğalgaz Malzeme A.Ş.', categoryName: 'Saha Enstrümanları' },
  { name: 'Keten ve Macun Seti', unit: 'paket', currency: 'TRY', basePrice: 45.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Sarf ve Montaj Malzemeleri' },
  { name: 'Askı Rotu (Tij) M8', unit: 'adet', currency: 'TRY', basePrice: 25.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Boru Askı ve Konsol Sistemleri (Rot, Dübel, Somun, L Profil)' },
  { name: 'Çelik Dübel M8 (Çakmalı)', unit: 'adet', currency: 'TRY', basePrice: 4.50, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Boru Askı ve Konsol Sistemleri (Rot, Dübel, Somun, L Profil)' },
  { name: 'Somun ve Pul M8', unit: 'adet', currency: 'TRY', basePrice: 1.50, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Boru Askı ve Konsol Sistemleri (Rot, Dübel, Somun, L Profil)' },
  { name: 'Klingerit Conta 2"', unit: 'adet', currency: 'TRY', basePrice: 5.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Boru Fitingsleri (Dirsek, Te, Redüksiyon - Kaynaklı)' },
  { name: 'Delikli U Profil 40x40x2mm', unit: 'adet', currency: 'TRY', basePrice: 180.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Boru Askı ve Konsol Sistemleri (Rot, Dübel, Somun, L Profil)' },
  { name: 'Antipas Boya (Gri)', unit: 'kg', currency: 'TRY', basePrice: 180.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Boru Askı ve Konsol Sistemleri (Rot, Dübel, Somun, L Profil)' },
];
