
export const productSeedData = [
  { name: 'Siyah Çelik Boru DN25 (Dikişli Orta Seri)', unit: 'metre', currency: 'TRY', basePrice: 185.00, supplierName: 'Demir Çelik Tedarik A.Ş.', categoryName: 'Siyah Çelik Boru' },
  { name: 'Siyah Çelik Boru DN50 (Dikişli Orta Seri)', unit: 'metre', currency: 'TRY', basePrice: 320.00, supplierName: 'Demir Çelik Tedarik A.Ş.', categoryName: 'Siyah Çelik Boru' },
  { name: 'PPRC Kompozit Boru Ø25 (Cam Elyaf Takviyeli)', unit: 'metre', currency: 'TRY', basePrice: 45.00, supplierName: 'Plastik Boru Sanayi', categoryName: 'PPRC Kompozit Boru' },
  { name: 'PPRC Kompozit Boru Ø40 (Cam Elyaf Takviyeli)', unit: 'metre', currency: 'TRY', basePrice: 85.00, supplierName: 'Plastik Boru Sanayi', categoryName: 'PPRC Kompozit Boru' },
  { name: 'Patent Dirsek DN50 (90° Kaynak Ağızlı)', unit: 'adet', currency: 'TRY', basePrice: 45.00, supplierName: 'Fitings Dünyası', categoryName: 'Patent Dirsek / Te / Redüksiyon' },
  { name: 'Patent Te DN50 (Kaynak Ağızlı)', unit: 'adet', currency: 'TRY', basePrice: 65.00, supplierName: 'Fitings Dünyası', categoryName: 'Patent Dirsek / Te / Redüksiyon' },
  { name: 'Patent Redüksiyon DN65/50', unit: 'adet', currency: 'TRY', basePrice: 55.00, supplierName: 'Fitings Dünyası', categoryName: 'Patent Dirsek / Te / Redüksiyon' },
  { name: 'Çelik Flanş DN65 PN16 (Boyunlu)', unit: 'adet', currency: 'TRY', basePrice: 250.00, supplierName: 'Fitings Dünyası', categoryName: 'Flanş (Düz/Boyunlu)' },
  { name: 'Düz Flanş DN50 PN16', unit: 'adet', currency: 'TRY', basePrice: 180.00, supplierName: 'Fitings Dünyası', categoryName: 'Flanş (Düz/Boyunlu)' },
  { name: 'Kelebek Vana DN50 (Lug Tipi EPDM)', unit: 'adet', currency: 'USD', basePrice: 85.00, supplierName: 'Vana Marketim', categoryName: 'Kelebek Vana' },
  { name: 'Kelebek Vana DN100 (Dişli Kutulu)', unit: 'adet', currency: 'USD', basePrice: 160.00, supplierName: 'Vana Marketim', categoryName: 'Kelebek Vana' },
  { name: 'Köşe Tip Termostatik Radyatör Vanası 1/2"', unit: 'adet', currency: 'EUR', basePrice: 12.00, supplierName: 'Vana Marketim', categoryName: 'Termostatik Radyatör Vanası' },
  { name: 'Düz Tip Termostatik Radyatör Vanası 1/2"', unit: 'adet', currency: 'EUR', basePrice: 12.00, supplierName: 'Vana Marketim', categoryName: 'Termostatik Radyatör Vanası' },
  { name: 'Statik Balans Vanası DN25', unit: 'adet', currency: 'EUR', basePrice: 65.00, supplierName: 'Vana Marketim', categoryName: 'Balans Vanası' },
  { name: 'Dinamik Balans Vanası DN40 (Fark Basınç)', unit: 'adet', currency: 'EUR', basePrice: 140.00, supplierName: 'Vana Marketim', categoryName: 'Balans Vanası' },
  { name: 'Prefabrik Cam Yünü Boru Yalıtımı 1" (Folyo Kaplı)', unit: 'metre', currency: 'TRY', basePrice: 45.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Prefabrik Boru Yalıtımı' },
  { name: 'Prefabrik Taş Yünü Boru Yalıtımı 2" (Folyo Kaplı)', unit: 'metre', currency: 'TRY', basePrice: 65.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Prefabrik Boru Yalıtımı' },
  { name: 'Somunlu Boru Kelepçesi 1" (Lastikli)', unit: 'adet', currency: 'TRY', basePrice: 8.50, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Boru Kelepçesi' },
  { name: 'Somunlu Boru Kelepçesi 2" (Lastikli)', unit: 'adet', currency: 'TRY', basePrice: 15.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Boru Kelepçesi' },
  { name: 'Siyah Çelik Boru 3" (Dikişsiz SCH40)', unit: 'metre', currency: 'TRY', basePrice: 550.00, supplierName: 'Demir Çelik Tedarik A.Ş.', categoryName: 'Siyah Çelik Boru (Soğutma)' },
  { name: 'Siyah Çelik Boru 4" (Dikişsiz SCH40)', unit: 'metre', currency: 'TRY', basePrice: 850.00, supplierName: 'Demir Çelik Tedarik A.Ş.', categoryName: 'Siyah Çelik Boru (Soğutma)' },
  { name: 'Bakır Boru 3/8" (Klima Tipi Tavlı)', unit: 'metre', currency: 'USD', basePrice: 12.00, supplierName: 'Bakır Boru A.Ş.', categoryName: 'Bakır Boru (VRF için)' },
  { name: 'Bakır Boru 5/8" (Klima Tipi Tavlı)', unit: 'metre', currency: 'USD', basePrice: 16.00, supplierName: 'Bakır Boru A.Ş.', categoryName: 'Bakır Boru (VRF için)' },
  { name: 'Elastomerik Kauçuk Köpüğü 19mm Levha (Class 0)', unit: 'm2', currency: 'TRY', basePrice: 450.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Elastomerik Kauçuk Köpüğü' },
  { name: 'Elastomerik Kauçuk Köpüğü 9mm Boru Tipi', unit: 'metre', currency: 'TRY', basePrice: 35.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Elastomerik Kauçuk Köpüğü' },
  { name: 'Kauçuk Bant 5cm (Kendinden Yapışkanlı)', unit: 'adet', currency: 'TRY', basePrice: 120.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Kauçuk Bant' },
  { name: 'Motorlu Vana 2 Yollu DN25 (On/Off)', unit: 'adet', currency: 'EUR', basePrice: 110.00, supplierName: 'Kontrol Vanaları Ltd.', categoryName: 'Motorlu Vana (2 veya 3 Yollu)' },
  { name: 'Motorlu Vana 3 Yollu DN32 (Oransal)', unit: 'adet', currency: 'EUR', basePrice: 240.00, supplierName: 'Kontrol Vanaları Ltd.', categoryName: 'Motorlu Vana (2 veya 3 Yollu)' },
  { name: 'Pislik Tutucu DN50 (Y Tipi Flanşlı)', unit: 'adet', currency: 'USD', basePrice: 65.00, supplierName: 'Vana Marketim', categoryName: 'Pislik Tutucu (Y Tipi)' },
  { name: 'Pislik Tutucu DN25 (Dişli Pirinç)', unit: 'adet', currency: 'USD', basePrice: 25.00, supplierName: 'Vana Marketim', categoryName: 'Pislik Tutucu (Y Tipi)' },
  { name: 'Metal Körüklü Kompansatör DN65 (Laynerli)', unit: 'adet', currency: 'USD', basePrice: 140.00, supplierName: 'Vana Marketim', categoryName: 'Kompansatör' },
  { name: 'Kauçuk Kompansatör DN100', unit: 'adet', currency: 'USD', basePrice: 85.00, supplierName: 'Vana Marketim', categoryName: 'Kompansatör' },
  { name: 'Poliüretan Soğuk Kelepçe Takozu 2"', unit: 'adet', currency: 'EUR', basePrice: 8.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Soğuk Kelepçe Takozu' },
  { name: 'PPRC Temiz Su Borusu Ø20 PN20', unit: 'metre', currency: 'TRY', basePrice: 25.00, supplierName: 'Plastik Boru Sanayi', categoryName: 'PPRC Temiz Su Borusu' },
  { name: 'PPRC Temiz Su Borusu Ø32 PN20', unit: 'metre', currency: 'TRY', basePrice: 55.00, supplierName: 'Plastik Boru Sanayi', categoryName: 'PPRC Temiz Su Borusu' },
  { name: 'Sessiz Pis Su Borusu Ø50 (3 Katmanlı)', unit: 'metre', currency: 'TRY', basePrice: 65.00, supplierName: 'Plastik Boru Sanayi', categoryName: 'Sessiz Pis Su Borusu' },
  { name: 'Sessiz Pis Su Borusu Ø110 (3 Katmanlı)', unit: 'metre', currency: 'TRY', basePrice: 180.00, supplierName: 'Plastik Boru Sanayi', categoryName: 'Sessiz Pis Su Borusu' },
  { name: 'PPRC Dirsek Ø25', unit: 'adet', currency: 'TRY', basePrice: 3.50, supplierName: 'Plastik Boru Sanayi', categoryName: 'PPRC Manşon/Dirsek/Te' },
  { name: 'PPRC Te Parçası Ø32', unit: 'adet', currency: 'TRY', basePrice: 5.50, supplierName: 'Plastik Boru Sanayi', categoryName: 'PPRC Manşon/Dirsek/Te' },
  { name: 'PPRC Manşon Ø20', unit: 'adet', currency: 'TRY', basePrice: 2.00, supplierName: 'Plastik Boru Sanayi', categoryName: 'PPRC Manşon/Dirsek/Te' },
  { name: 'Küresel Vana 1" (Pirinç PN25)', unit: 'adet', currency: 'TRY', basePrice: 110.00, supplierName: 'Vana Marketim', categoryName: 'Küresel Vana (Su)' },
  { name: 'Küresel Vana 1/2" (Pirinç PN25)', unit: 'adet', currency: 'TRY', basePrice: 65.00, supplierName: 'Vana Marketim', categoryName: 'Küresel Vana (Su)' },
  { name: 'Yaylı Çekvalf 1" (Pirinç)', unit: 'adet', currency: 'TRY', basePrice: 85.00, supplierName: 'Vana Marketim', categoryName: 'Çekvalf' },
  { name: 'Çalpara Çekvalf 1 1/4" (Pirinç)', unit: 'adet', currency: 'TRY', basePrice: 120.00, supplierName: 'Vana Marketim', categoryName: 'Çekvalf' },
  { name: 'Basınç Düşürücü 3/4" (Manometreli)', unit: 'adet', currency: 'EUR', basePrice: 45.00, supplierName: 'Vana Marketim', categoryName: 'Basınç Düşürücü' },
  { name: 'Gömme Rezervuar Seti (Tuğla Duvar Uyumlu)', unit: 'adet', currency: 'TRY', basePrice: 1850.00, supplierName: 'Vitrifiye Toptan A.Ş.', categoryName: 'Gömme Rezervuar' },
  { name: 'Paslanmaz Yer Süzgeci 10x10 (Koku Önleyicili)', unit: 'adet', currency: 'TRY', basePrice: 250.00, supplierName: 'Vitrifiye Toptan A.Ş.', categoryName: 'Yer Süzgeci' },
  { name: 'Yangın Borusu 2" (Kırmızı Astarlı)', unit: 'metre', currency: 'TRY', basePrice: 380.00, supplierName: 'Demir Çelik Boru A.Ş.', categoryName: 'Yangın Borusu' },
  { name: 'Yangın Borusu 3" (Kırmızı Astarlı)', unit: 'metre', currency: 'TRY', basePrice: 650.00, supplierName: 'Demir Çelik Boru A.Ş.', categoryName: 'Yangın Borusu' },
  { name: 'Yivli Rijit Kaplin 2" (FM/UL)', unit: 'adet', currency: 'USD', basePrice: 6.50, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Yivli Bağlantı Parçaları' },
  { name: 'Yivli Dirsek 90° 3" (FM/UL)', unit: 'adet', currency: 'USD', basePrice: 12.50, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Yivli Bağlantı Parçaları' },
  { name: 'Yivli Te 2" (FM/UL)', unit: 'adet', currency: 'USD', basePrice: 14.00, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Yivli Bağlantı Parçaları' },
  { name: 'Pendent (Sarkık) Sprinkler K:5.6 68°C', unit: 'adet', currency: 'USD', basePrice: 7.50, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Sprinkler Başlığı' },
  { name: 'Upright (Dik) Sprinkler K:8.0 68°C', unit: 'adet', currency: 'USD', basePrice: 9.50, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Sprinkler Başlığı' },
  { name: 'Islak Alarm Vanası İstasyonu DN100 (Set)', unit: 'set', currency: 'USD', basePrice: 1300.00, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Islak Alarm Vanası' },
  { name: 'İzleme Anahtarlı Kelebek Vana DN100 (OS&Y)', unit: 'adet', currency: 'USD', basePrice: 220.00, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'İzleme Anahtarlı Kelebek Vana' },
  { name: 'Akış Anahtarı (Flow Switch) 2"', unit: 'adet', currency: 'USD', basePrice: 85.00, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Akış Anahtarı (Flow Switch)' },
  { name: 'Sıva Altı Yangın Dolabı (Tüplü)', unit: 'adet', currency: 'TRY', basePrice: 4500.00, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Yangın Dolabı' },
  { name: 'Sıva Üstü Yangın Dolabı (Tüpsüz)', unit: 'adet', currency: 'TRY', basePrice: 3200.00, supplierName: 'Yangın Güvenlik A.Ş.', categoryName: 'Yangın Dolabı' },
  { name: 'Galvaniz Sac Levha 0.70mm', unit: 'kg', currency: 'USD', basePrice: 1.70, supplierName: 'Havalandırma Dünyası', categoryName: 'Galvaniz Sac Levha' },
  { name: 'Galvaniz Sac Levha 1.20mm', unit: 'kg', currency: 'USD', basePrice: 1.70, supplierName: 'Havalandırma Dünyası', categoryName: 'Galvaniz Sac Levha' },
  { name: 'Kanal Flanş Profili 25mm', unit: 'metre', currency: 'TRY', basePrice: 22.00, supplierName: 'Havalandırma Dünyası', categoryName: 'Flanş Profili' },
  { name: 'Kanal Flanş Profili 30mm', unit: 'metre', currency: 'TRY', basePrice: 28.00, supplierName: 'Havalandırma Dünyası', categoryName: 'Flanş Profili' },
  { name: 'Kanal Köşe Parçası 25mm', unit: 'adet', currency: 'TRY', basePrice: 2.50, supplierName: 'Havalandırma Dünyası', categoryName: 'Köşe Parçası' },
  { name: 'Alüminyum Esnek Hava Kanalı Ø200 (İzoleli)', unit: 'kutu', currency: 'USD', basePrice: 45.00, supplierName: 'Havalandırma Dünyası', categoryName: 'Esnek Hava Kanalı (Fleks)' },
  { name: 'Yangın Damperi 400x400 (72°C Sigortalı)', unit: 'adet', currency: 'EUR', basePrice: 150.00, supplierName: 'Havalandırma Aksesuar Ltd.', categoryName: 'Yangın Damperi' },
  { name: 'Motorlu Yangın Damperi 500x500', unit: 'adet', currency: 'EUR', basePrice: 350.00, supplierName: 'Havalandırma Aksesuar Ltd.', categoryName: 'Yangın Damperi' },
  { name: 'Volüm Damperi 300x300 (Kollu)', unit: 'adet', currency: 'EUR', basePrice: 60.00, supplierName: 'Havalandırma Aksesuar Ltd.', categoryName: 'Volüm Damperi' },
  { name: 'Toplayıcı Menfez 400x400 (Damperli)', unit: 'adet', currency: 'TRY', basePrice: 350.00, supplierName: 'Menfez Market', categoryName: 'Toplayıcı/Dağıtıcı Menfez' },
  { name: 'Dağıtıcı Menfez 500x500 (Çift Sıra Kanatlı)', unit: 'adet', currency: 'TRY', basePrice: 420.00, supplierName: 'Menfez Market', categoryName: 'Toplayıcı/Dağıtıcı Menfez' },
  { name: 'Yanmaz Akustik Yalıtım Süngeri (Yapışkanlı)', unit: 'm2', currency: 'EUR', basePrice: 12.00, supplierName: 'İzolasyoncu Baba', categoryName: 'Akustik Yalıtım Süngeri' },
  { name: 'Doğalgaz Çelik Borusu 1" (PE Kaplı Toprak Altı)', unit: 'metre', currency: 'TRY', basePrice: 210.00, supplierName: 'Doğalgaz Malzeme A.Ş.', categoryName: 'Doğalgaz Çelik Borusu' },
  { name: 'Doğalgaz Çelik Borusu 2" (TS 6047)', unit: 'metre', currency: 'TRY', basePrice: 380.00, supplierName: 'Doğalgaz Malzeme A.Ş.', categoryName: 'Doğalgaz Çelik Borusu' },
  { name: 'Doğalgaz Küresel Vanası 1" (MOP5)', unit: 'adet', currency: 'TRY', basePrice: 180.00, supplierName: 'Vana Marketim', categoryName: 'Doğalgaz Küresel Vanası' },
  { name: 'Doğalgaz Solenoid Vana 1" (Ex-Proof)', unit: 'adet', currency: 'EUR', basePrice: 120.00, supplierName: 'Otomasyon Market', categoryName: 'Solenoid Vana' },
  { name: 'Doğalgaz Flex Hortum 1/2" (70cm Makaronlu)', unit: 'adet', currency: 'TRY', basePrice: 120.00, supplierName: 'Doğalgaz Malzeme A.Ş.', categoryName: 'Esnek Metal Hortum (Flex)' },
  { name: 'Keten ve Sızdırmazlık Macunu Seti', unit: 'paket', currency: 'TRY', basePrice: 45.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Keten & Macun / Loctite' },
  { name: 'Galvanizli Askı Rotu (Tij) M8', unit: 'adet', currency: 'TRY', basePrice: 25.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Askı Rotu (Tij)' },
  { name: 'Galvanizli Askı Rotu (Tij) M10', unit: 'adet', currency: 'TRY', basePrice: 35.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Askı Rotu (Tij)' },
  { name: 'Çakmalı Çelik Dübel M8', unit: 'adet', currency: 'TRY', basePrice: 4.50, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Çelik Dübel' },
  { name: 'Somun ve Pul Takımı M8', unit: 'adet', currency: 'TRY', basePrice: 1.50, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Somun & Pul' },
  { name: 'Klingerit Conta 2" (Buhar/Sıcak Su)', unit: 'adet', currency: 'TRY', basePrice: 5.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Conta' },
  { name: 'EPDM Conta 2" (Soğuk Su)', unit: 'adet', currency: 'TRY', basePrice: 3.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Conta' },
  { name: 'Delikli U Profil 40x40x2mm (2mt)', unit: 'adet', currency: 'TRY', basePrice: 180.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Profil' },
  { name: 'Antipas Boya (Gri/Kırmızı)', unit: 'kg', currency: 'TRY', basePrice: 180.00, supplierName: 'Hırdavat Toptan A.Ş.', categoryName: 'Boya' },
];

    