
export type InitialInstallationType = {
  name: string;
  description: string;
};

export const initialInstallationTypesData: InitialInstallationType[] = [
  // 1. ISITMA TESİSATI
  { name: 'ISITMA TESİSATI', description: 'Binaların ısıtılması ve sıcak su ihtiyaçlarının karşılanması.' },
  { name: 'ISITMA TESİSATI > Isı Üretim Merkezi', description: 'Sistemin kalbi olan ısıtma cihazları ve ana bileşenleri.' },
  { name: 'ISITMA TESİSATI > Isı Üretim Merkezi > Kazanlar (Dilimli / Çelik / Yoğuşmalı)', description: 'Sistemin ana ısı üreticisi.' },
  { name: 'ISITMA TESİSATI > Isı Üretim Merkezi > Brülörler ve Gaz Yolu Armatürleri', description: 'Yakıtı yakarak ısı enerjisi üreten ekipmanlar.' },
  { name: 'ISITMA TESİSATI > Isı Üretim Merkezi > Duman Bacaları (Çift Cidarlı Paslanmaz Çelik)', description: 'Yanma gazlarının güvenli şekilde atmosfere atılması.' },
  { name: 'ISITMA TESİSATI > Isı Üretim Merkezi > Kazan Kontrol Panelleri (Kazan Üzeri)', description: 'Kazanların çalışmasını kontrol eden paneller.' },
  { name: 'ISITMA TESİSATI > Isıtma Armatürleri ve Ekipmanları', description: 'Sistemin verimli ve güvenli çalışması için gerekli yardımcı ekipmanlar.' },
  { name: 'ISITMA TESİSATI > Isıtma Armatürleri ve Ekipmanları > Hava Ayırıcılar ve Tortu Tutucular (Spirovent vb.)', description: 'Sudaki hava ve tortuyu ayrıştıran ekipmanlar.' },
  { name: 'ISITMA TESİSATI > Isıtma Armatürleri ve Ekipmanları > Denge Kapları (Hydraulic Separator)', description: 'Hidrolik devreleri birbirinden ayıran dengeleme tankı.' },
  { name: 'ISITMA TESİSATI > Isıtma Armatürleri ve Ekipmanları > Genleşme Tankları (Membranlı - Isıtma Tipi)', description: 'Isınan suyun genleşmesini kompanse eden tanklar.' },
  { name: 'ISITMA TESİSATI > Isıtma Armatürleri ve Ekipmanları > Otomatik Su Besleme Ünitesi', description: 'Sistemdeki su eksikliğini otomatik tamamlayan üniteler.' },
  { name: 'ISITMA TESİSATI > Isıtma Pompa Grupları', description: 'Isıtıcı akışkanın sistem içinde sirkülasyonunu sağlayan pompalar.' },
  { name: 'ISITMA TESİSATI > Isıtma Pompa Grupları > Kazan Şönt Pompaları', description: 'Kazan suyu sıcaklığını dengeleyen pompalar.' },
  { name: 'ISITMA TESİSATI > Isıtma Pompa Grupları > Primer Devre Sirkülasyon Pompaları', description: 'Kazan ile ana dağıtım arasındaki dolaşım pompaları.' },
  { name: 'ISITMA TESİSATI > Isıtma Pompa Grupları > Sekonder Devre Sirkülasyon Pompaları (Frekans Konvertörlü)', description: 'Bölgelere suyu taşıyan, değişken hızlı pompalar.' },
  { name: 'ISITMA TESİSATI > Isıtma Boru Hattı Bileşenleri', description: 'Isıtıcı akışkanın taşındığı boru ve yardımcı malzemeler.' },
  { name: 'ISITMA TESİSATI > Isıtma Boru Hattı Bileşenleri > Siyah Çelik Borular (Dikişli/Dikişsiz)', description: 'Ana ısıtma hatlarında kullanılan borular.' },
  { name: 'ISITMA TESİSATI > Isıtma Boru Hattı Bileşenleri > Boru Fitingsleri (Dirsek, Te, Redüksiyon - Kaynaklı)', description: 'Boruları birleştirmek ve yönlendirmek için kullanılan parçalar.' },
  { name: 'ISITMA TESİSATI > Isıtma Boru Hattı Bileşenleri > Boru Askı ve Konsol Sistemleri (Rot, Dübel, Somun, L Profil)', description: 'Boruların sabitlenmesi ve taşınması için kullanılan sistemler.' },
  { name: 'ISITMA TESİSATI > Isıtma Boru Hattı Bileşenleri > Boru İzolasyonu (Cam Yünü / Taş Yünü / Alüminyum Kaplama)', description: 'Isı kaybını önleyen yalıtım malzemeleri.' },
  { name: 'ISITMA TESİSATI > Isıtma Vana Grubu', description: 'Akışı kontrol etmek, kesmek ve dengelemek için kullanılan vanalar.' },
  { name: 'ISITMA TESİSATI > Isıtma Vana Grubu > Kelebek Vanalar (Dişli kutulu / Kollu)', description: 'Açma-kapama amaçlı kullanılan vanalar.' },
  { name: 'ISITMA TESİSATI > Isıtma Vana Grubu > Pislik Tutucular', description: 'Tesisattaki katı partikülleri filtreleyen elemanlar.' },
  { name: 'ISITMA TESİSATI > Isıtma Vana Grubu > Çekvalfler (Yaylı / Çalpara)', description: 'Akışın tek yönlü olmasını sağlayan vanalar.' },
  { name: 'ISITMA TESİSATI > Isıtma Vana Grubu > Balans Vanaları (Statik / Dinamik)', description: 'Devrelerdeki su debisini ayarlayan vanalar.' },
  { name: 'ISITMA TESİSATI > Isıtma Vana Grubu > Kompansatörler (Metal Körüklü / Kauçuk)', description: 'Termal genleşmeyi ve titreşimi absorbe eden elemanlar.' },

  // 2. SOĞUTMA TESİSATI
  { name: 'SOĞUTMA TESİSATI', description: 'Binaların soğutulması ve iklimlendirilmesi.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Üretim', description: 'Soğutma enerjisinin üretildiği merkezi gruplar.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Üretim > Su Soğutma Grupları (Chiller - Vidalı/Scroll Kompresörlü)', description: 'Suyu soğutarak sisteme gönderen ana üniteler.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Üretim > Soğutma Kuleleri (Açık/Kapalı - Aksiyel/Radyal Fanlı)', description: 'Chiller’ın kondenser suyunu soğutan ekipmanlar.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Üretim > Chiller Vibrasyon Takozları ve Kaideleri', description: 'Chiller grubunun titreşimini sönümleyen elemanlar.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Suyu Şartlandırma', description: 'Sistem suyunun korozyon ve kirece karşı korunması.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Suyu Şartlandırma > Kimyasal Dozaj Pompaları', description: 'Sisteme kimyasal enjekte eden pompalar.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Suyu Şartlandırma > Filtrasyon Sistemleri (Kum Seperatörü)', description: 'Sudaki partikülleri temizleyen filtreler.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Suyu Şartlandırma > Otomatik Blöf Sistemleri', description: 'Kule suyundaki mineral yoğunluğunu kontrol eden sistem.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Borulaması ve Yalıtım', description: 'Soğuk suyun taşındığı hatlar ve ısı kazancını önleyen yalıtım.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Borulaması ve Yalıtım > Çelik Borular (Soğutma Hattı)', description: 'Soğutma hatlarında kullanılan borular.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Borulaması ve Yalıtım > Elastomerik Kauçuk Köpüğü İzolasyonu', description: 'Yoğuşmayı ve ısı kazancını önleyen buhar kesici yalıtım.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Borulaması ve Yalıtım > Boru Askıları (İzolasyon Takozlu - Soğuk Köprü Engelleyici)', description: 'Isı köprüsü oluşturmayan özel askı sistemleri.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Uç Birim Bağlantıları', description: 'Fan-coil gibi uç elemanların sisteme bağlantı parçaları.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Uç Birim Bağlantıları > Fan-Coil Bağlantı Paketleri (Fleks hortum, küresel vana, pislik tutucu seti)', description: 'Fan-coil montajı için hazır setler.' },
  { name: 'SOĞUTMA TESİSATI > Soğutma Uç Birim Bağlantıları > Motorlu Vanalar (2 Yollu / 3 Yollu - On/Off veya Oransal)', description: 'Uç birimlerin su akışını kontrol eden vanalar.' },

  // 3. HAVALANDIRMA VE KLİMA
  { name: 'HAVALANDIRMA VE KLİMA', description: 'İç mekan hava kalitesinin sağlanması ve şartlandırılması.' },
  { name: 'HAVALANDIRMA VE KLİMA > Havalandırma Cihazları', description: 'Havayı işleyen ve hareket ettiren ana ekipmanlar.' },
  { name: 'HAVALANDIRMA VE KLİMA > Havalandırma Cihazları > Klima Santralleri (Hücre yapıları, Bataryalar, Fanlar)', description: 'Havayı temizleyen, ısıtan, soğutan ve nemlendiren modüler cihazlar.' },
  { name: 'HAVALANDIRMA VE KLİMA > Havalandırma Cihazları > Filtre Grupları (G4 Kaset, F7 Torba, Hepa Filtreler)', description: 'Hava içindeki partikülleri tutan filtreler.' },
  { name: 'HAVALANDIRMA VE KLİMA > Havalandırma Cihazları > Nemlendirici Üniteler (Buharlı / Pedli)', description: 'Havaya nem ekleyen üniteler.' },
  { name: 'HAVALANDIRMA VE KLİMA > Hava Kanalları ve Altyapı', description: 'Havayı taşıyan kanallar ve montaj bileşenleri.' },
  { name: 'HAVALANDIRMA VE KLİMA > Hava Kanalları ve Altyapı > Galvaniz Hava Kanalları (Levha kalınlıklarına göre: 0.70mm, 1.00mm, 1.20mm)', description: 'Genel havalandırma için kullanılan sac kanallar.' },
  { name: 'HAVALANDIRMA VE KLİMA > Hava Kanalları ve Altyapı > Paslanmaz Çelik Kanallar (Mutfak Egzoz vb.)', description: 'Hijyenik veya korozif ortamlar için kullanılan kanallar.' },
  { name: 'HAVALANDIRMA VE KLİMA > Hava Kanalları ve Altyapı > Hava Kanalı Flanş ve Köşe Parçaları', description: 'Kanal montajında kullanılan birleştirme elemanları.' },
  { name: 'HAVALANDIRMA VE KLİMA > Hava Kanalları ve Altyapı > Kanal İzolasyonu (Akustik / Termal - İçten/Dıştan)', description: 'Kanalda ses ve ısı yalıtımı sağlayan malzemeler.' },
  { name: 'HAVALANDIRMA VE KLİMA > Kanal Aksesuarları', description: 'Hava akışını yönetmek ve kontrol etmek için kullanılan parçalar.' },
  { name: 'HAVALANDIRMA VE KLİMA > Kanal Aksesuarları > Hava Damperleri (Manuel Volüm Damperi)', description: 'Hava debisini manuel olarak ayarlayan damperler.' },
  { name: 'HAVALANDIRMA VE KLİMA > Kanal Aksesuarları > Yangın Damperleri (Sigortalı / Motorlu)', description: 'Yangın anında hava geçişini engelleyen damperler.' },
  { name: 'HAVALANDIRMA VE KLİMA > Kanal Aksesuarları > Susturucular (Kulisli Tip)', description: 'Kanal içindeki fan sesini sönümleyen elemanlar.' },
  { name: 'HAVALANDIRMA VE KLİMA > Kanal Aksesuarları > Fleksible Bağlantılar (Cihaz ağızları için konnektörler)', description: 'Cihaz titreşiminin kanala geçmesini önleyen bağlantılar.' },
  { name: 'HAVALANDIRMA VE KLİMA > Kanal Aksesuarları > Müdahale Kapakları', description: 'Kanal içinde bakım ve temizlik için erişim kapakları.' },
  { name: 'HAVALANDIRMA VE KLİMA > Üfleme ve Emiş Elemanları', description: 'Havanın mahale dağıtıldığı veya mahalden toplandığı elemanlar.' },
  { name: 'HAVALANDIRMA VE KLİMA > Üfleme ve Emiş Elemanları > Menfezler (Dağıtıcı/Toplayıcı - Damperli/Dampersiz)', description: 'Hava üfleme veya emişi için kullanılan ızgaralar.' },
  { name: 'HAVALANDIRMA VE KLİMA > Üfleme ve Emiş Elemanları > Difüzörler (Kare, Slot, Girdaplı)', description: 'Havanın ortama homojen dağılmasını sağlayan elemanlar.' },
  { name: 'HAVALANDIRMA VE KLİMA > Üfleme ve Emiş Elemanları > Anemostadlar', description: 'Genellikle emiş için kullanılan hava dağıtım elemanları.' },
  { name: 'HAVALANDIRMA VE KLİMA > Üfleme ve Emiş Elemanları > Plenum Kutuları (İzoleli)', description: 'Menfez ve difüzörlerin arkasına konan hava toplama kutuları.' },
  { name: 'HAVALANDIRMA VE KLİMA > VRF / Klima Bakır Borulama', description: 'VRF ve split klima sistemlerinin soğutucu akışkan ve drenaj hatları.' },
  { name: 'HAVALANDIRMA VE KLİMA > VRF / Klima Bakır Borulama > Bakır Borular (Sert / Tavlı)', description: 'Soğutucu akışkanı taşıyan borular.' },
  { name: 'HAVALANDIRMA VE KLİMA > VRF / Klima Bakır Borulama > Refnet (Dağıtıcı) Jointler', description: 'Bakır boru hattını iç ünitelere dağıtan Y-tipi parçalar.' },
  { name: 'HAVALANDIRMA VE KLİMA > VRF / Klima Bakır Borulama > Konsol ve Kablo Tavaları', description: 'Dış ünitelerin montajı ve boruların taşınması için kullanılır.' },
  { name: 'HAVALANDIRMA VE KLİMA > VRF / Klima Bakır Borulama > Drenaj Hattı (PVC Borulama)', description: 'İç ünitelerde oluşan yoğuşma suyunun tahliyesi.' },

  // 4. SIHHİ TESİSAT
  { name: 'SIHHİ TESİSAT', description: 'Binanın su ihtiyacının karşılanması ve atık suyun uzaklaştırılması.' },
  { name: 'SIHHİ TESİSAT > Sıcak Su Üretim', description: 'Kullanım sıcak suyunun hazırlandığı ekipmanlar.' },
  { name: 'SIHHİ TESİSAT > Sıcak Su Üretim > Boylerler (Tek/Çift Serpantinli)', description: 'Isıtma kazanından veya güneş enerjisinden aldığı ısıyla suyu depolayan tanklar.' },
  { name: 'SIHHİ TESİSAT > Sıcak Su Üretim > Elektrikli Rezistanslar', description: 'Boylerler için yedek veya ana ısıtıcı.' },
  { name: 'SIHHİ TESİSAT > Sıcak Su Üretim > Plakalı Isı Eşanjörleri', description: 'Anlık sıcak su üretimi için kullanılan kompakt eşanjörler.' },
  { name: 'SIHHİ TESİSAT > Pompalar ve Hidroforlar', description: 'Su basınçlandırma ve sirkülasyonu.' },
  { name: 'SIHHİ TESİSAT > Pompalar ve Hidroforlar > Kullanım Suyu Hidroforları (Frekans konvertörlü panosu dahil)', description: 'Şebeke basıncının yetersiz olduğu yerlerde su basıncını artıran sistemler.' },
  { name: 'SIHHİ TESİSAT > Pompalar ve Hidroforlar > Sirkülasyon Pompaları (Bronz gövde - Lejyonella riskine karşı)', description: 'Sıcak suyun hatlarda sürekli dolaşımını sağlar.' },
  { name: 'SIHHİ TESİSAT > Pompalar ve Hidroforlar > Pis Su Dalgıç Pompaları (Kızaklı sistem, toplu çekvalf dahil)', description: 'Kot altındaki atık suları ana gidere basan pompalar.' },
  { name: 'SIHHİ TESİSAT > Borulama Sistemleri', description: 'Temiz ve pis suyun taşındığı borular ve ek parçaları.' },
  { name: 'SIHHİ TESİSAT > Borulama Sistemleri > PPRC Temiz Su Boruları ve Fitingsleri', description: 'Standart temiz su tesisat boruları.' },
  { name: 'SIHHİ TESİSAT > Borulama Sistemleri > Kompozit Folyolu Borular (Sıcak Su için)', description: 'Termal genleşmesi az olan sıcak su boruları.' },
  { name: 'SIHHİ TESİSAT > Borulama Sistemleri > PVC Pis Su Boruları (B Tipi / BD Tipi)', description: 'Standart atık su ve drenaj boruları.' },
  { name: 'SIHHİ TESİSAT > Borulama Sistemleri > Sessiz Borular (Astolan / Mineral katkılı)', description: 'Ses yalıtımı artırılmış atık su boruları.' },
  { name: 'SIHHİ TESİSAT > Tesisat Aksesuarları', description: 'Sıhhi tesisatın yardımcı ve kontrol elemanları.' },
  { name: 'SIHHİ TESİSAT > Tesisat Aksesuarları > Basınç Düşürücüler', description: 'Yüksek şebeke basıncını istenen seviyeye düşüren vanalar.' },
  { name: 'SIHHİ TESİSAT > Tesisat Aksesuarları > Koç Darbesi Önleyiciler', description: 'Ani vana kapanmalarında oluşan basınç şokunu emen cihazlar.' },
  { name: 'SIHHİ TESİSAT > Tesisat Aksesuarları > Süzgeçler (Yer Süzgeci, Balkon Süzgeci, Çatı Süzgeci)', description: 'Su toplama ve drenaj noktaları.' },
  { name: 'SIHHİ TESİSAT > Tesisat Aksesuarları > Yağ Ayırıcılar (Mutfak hatları için)', description: 'Mutfak atık sularındaki yağı ayrıştıran sistemler.' },

  // 5. YANGIN TESİSATI
  { name: 'YANGIN TESİSATI', description: 'Yangına müdahale ve can/mal güvenliği sistemleri.' },
  { name: 'YANGIN TESİSATI > Pompa İstasyonu Detayı', description: 'Yangın söndürme sistemine basınçlı su sağlayan merkez.' },
  { name: 'YANGIN TESİSATI > Pompa İstasyonu Detayı > Ana Pompa (Dizel) + Yakıt Tankı + Susturucu', description: 'Elektrik kesintisinde devreye giren ana yangın pompası.' },
  { name: 'YANGIN TESİSATI > Pompa İstasyonu Detayı > Yedek Pompa (Elektrikli)', description: 'Ana pompanın yedeği olan elektrikli pompa.' },
  { name: 'YANGIN TESİSATI > Pompa İstasyonu Detayı > Jokey Pompa', description: 'Tesisattaki küçük basınç kayıplarını karşılayan pompa.' },
  { name: 'YANGIN TESİSATI > Pompa İstasyonu Detayı > Pompa Kontrol Panoları (UL/FM onaylı)', description: 'Yangın pompalarını yöneten onaylı kontrol panoları.' },
  { name: 'YANGIN TESİSATI > Pompa İstasyonu Detayı > Test Hattı ve Debimetre (Akış ölçer)', description: 'Pompaların performansını test etmek için kullanılan hat.' },
  { name: 'YANGIN TESİSATI > Saha Ekipmanları (Zone Bazlı)', description: 'Yangın bölgelerini kontrol eden ve izleyen ekipmanlar.' },
  { name: 'YANGIN TESİSATI > Saha Ekipmanları (Zone Bazlı) > Islak Alarm Vanaları (Alarm Check Valve)', description: 'Bir bölgede su akışı olduğunda alarm veren vana.' },
  { name: 'YANGIN TESİSATI > Saha Ekipmanları (Zone Bazlı) > Akış Anahtarları (Flow Switch)', description: 'Sprinkler hattında su akışını algılayan anahtarlar.' },
  { name: 'YANGIN TESİSATI > Saha Ekipmanları (Zone Bazlı) > İzleme Anahtarlı Kelebek Vanalar', description: 'Açık/kapalı durumu otomasyona bildiren vanalar.' },
  { name: 'YANGIN TESİSATI > Saha Ekipmanları (Zone Bazlı) > Test ve Drenaj Vanaları', description: 'Hatların test ve boşaltılması için kullanılan vanalar.' },
  { name: 'YANGIN TESİSATI > Borulama ve Sismik', description: 'Yangın suyu borulaması ve deprem koruma elemanları.' },
  { name: 'YANGIN TESİSATI > Borulama ve Sismik > Siyah Çelik Boru (SCH40 - Yivli veya Kaynaklı)', description: 'Yangın tesisatında kullanılan standart boru tipi.' },
  { name: 'YANGIN TESİSATI > Borulama ve Sismik > Yivli Bağlantı Parçaları (Kaplin, Dirsek, Te)', description: 'Kaynak gerektirmeyen hızlı boru montaj parçaları.' },
  { name: 'YANGIN TESİSATI > Borulama ve Sismik > Sismik Halatlar ve Sismik Askı Setleri', description: 'Deprem sırasında boru hattının bütünlüğünü koruyan sistemler.' },

  // 6. OTOMASYON VE SAHA KONTROL
  { name: 'OTOMASYON VE SAHA KONTROL (Mekanik Elektrik)', description: 'Mekanik sistemlerin kontrolü, izlenmesi ve yönetilmesi.' },
  { name: 'OTOMASYON VE SAHA KONTROL (Mekanik Elektrik) > Saha Enstrümanları', description: 'Sistemden veri toplayan sensörler ve anahtarlar.' },
  { name: 'OTOMASYON VE SAHA KONTROL (Mekanik Elektrik) > Saha Enstrümanları > Daldırma Tipi Sıcaklık Sensörleri', description: 'Boru içindeki akışkan sıcaklığını ölçer.' },
  { name: 'OTOMASYON VE SAHA KONTROL (Mekanik Elektrik) > Saha Enstrümanları > Kanal Tipi Nem ve Sıcaklık Sensörleri', description: 'Hava kanalı içindeki hava şartlarını ölçer.' },
  { name: 'OTOMASYON VE SAHA KONTROL (Mekanik Elektrik) > Saha Enstrümanları > Fark Basınç Anahtarları (Filtre kirlilik için)', description: 'Filtrelerin kirlendiğini algılayan anahtarlar.' },
  { name: 'OTOMASYON VE SAHA KONTROL (Mekanik Elektrik) > Saha Enstrümanları > Basınç Transmitterleri', description: 'Sistem basıncını sürekli ölçüp otomasyona bildiren sensörler.' },
  { name: 'OTOMASYON VE SAHA KONTROL (Mekanik Elektrik) > Kontrol Panelleri', description: 'Saha ekipmanlarını yöneten ve güç dağıtan panolar.' },
  { name: 'OTOMASYON VE SAHA KONTROL (Mekanik Elektrik) > Kontrol Panelleri > MCC Panoları (Güç Panoları)', description: 'Motorlar ve pompalar için motor koruma ve yol verme panoları.' },
  { name: 'OTOMASYON VE SAHA KONTROL (Mekanik Elektrik) > Kontrol Panelleri > DDC Panoları (Kontrol Panoları)', description: 'Otomasyon senaryolarını çalıştıran programlanabilir kontrolcü panoları.' },
  { name: 'OTOMASYON VE SAHA KONTROL (Mekanik Elektrik) > Kontrol Panelleri > Frekans İnvertörleri (Sürücüler)', description: 'Pompa ve fan motorlarının hızını kontrol ederek enerji tasarrufu sağlayan cihazlar.' },

  // 7. GENEL GİDERLER VE DİĞERLERİ
  { name: 'GENEL GİDERLER VE DİĞERLERİ', description: 'Sistemlere doğrudan atanamayan ortak maliyet kalemleri.' },
  { name: 'GENEL GİDERLER VE DİĞERLERİ > Test ve Devreye Alma', description: 'Sistemlerin çalışır duruma getirilmesi ve ayarlarının yapılması.' },
  { name: 'GENEL GİDERLER VE DİĞERLERİ > Test ve Devreye Alma > Boru Basınç Testleri', description: 'Boru hatlarının sızdırmazlık testleri.' },
  { name: 'GENEL GİDERLER VE DİĞERLERİ > Test ve Devreye Alma > Hava Kanalı Sızdırmazlık Testleri', description: 'Hava kanallarındaki kaçak testleri.' },
  { name: 'GENEL GİDERLER VE DİĞERLERİ > Test ve Devreye Alma > Balanslama (Su ve Hava Ayarları)', description: 'Sistemdeki su ve hava debilerinin projedeki değerlere ayarlanması.' },
  { name: 'GENEL GİDERLER VE DİĞERLERİ > Etiketleme ve İşaretleme', description: 'Tesisatın tanınması ve bakım kolaylığı için yapılan işaretlemeler.' },
  { name: 'GENEL GİDERLER VE DİĞERLERİ > Etiketleme ve İşaretleme > Boru Yön Okları ve Etiketleri', description: 'Akışkan yönünü ve içeriğini belirten etiketler.' },
  { name: 'GENEL GİDERLER VE DİĞERLERİ > Etiketleme ve İşaretleme > Vana Numaralandırma Plakaları', description: 'Vanaların projeyle eşleştirilmesini sağlayan metal plakalar.' },
  { name: 'GENEL GİDERLER VE DİĞERLERİ > Etiketleme ve İşaretleme > Ekipman Tanıtım Kartları', description: 'Cihazların teknik bilgilerini içeren tanıtım kartları.' }
];
